version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_HOST=${RENDER_EXTERNAL_HOSTNAME}
      - WEBHOOK_URL=https://${RENDER_EXTERNAL_HOSTNAME}/
      - GENERIC_TIMEZONE=Africa/Addis_Ababa

      # --- Database (PostgreSQL) ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      

      
